name: Ejecutar Scraper

on:
  schedule:
    - cron: "0 13 * * *"   # Todos los días a las 10 AM Argentina (13 UTC)
  workflow_dispatch:        # Permite correrlo manualmente desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraper
        run: node index.js
